var resources;

resources = [
  {
    type: 'clay',
    x: 3104,
    y: 3437,
    size: 'large'
  }, {
    type: 'clay',
    x: 2977,
    y: 3734,
    size: 'large'
  }, {
    type: 'clay',
    x: 3005,
    y: 3853,
    size: 'large'
  }, {
    type: 'clay',
    x: 2853,
    y: 490,
    size: 'medium'
  }, {
    type: 'clay',
    x: 1456,
    y: 328,
    size: 'large'
  }, {
    type: 'clay',
    x: 918,
    y: 810,
    size: 'medium'
  }, {
    type: 'clay',
    x: 974,
    y: 3815,
    size: 'large'
  }, {
    type: 'tar',
    x: 824,
    y: 683,
    size: 'small'
  }, {
    type: 'sand',
    x: 3084,
    y: 3651,
    size: 'large'
  }, {
    type: 'sand',
    x: 1116,
    y: 880,
    size: 'small'
  }, {
    type: 'clay',
    x: 2370,
    y: 374,
    size: 'large'
  }, {
    type: 'tar',
    x: 2663,
    y: 371,
    size: 'small'
  }, {
    type: 'tar',
    x: 1050,
    y: 490,
    size: 'small'
  }, {
    type: 'peat',
    x: 2790,
    y: 862,
    size: 'large'
  }, {
    type: 'tar',
    x: 611,
    y: 2851,
    size: 'small'
  }, {
    type: 'clay',
    x: 805,
    y: 2417,
    size: 'medium'
  }, {
    type: 'tar',
    size: 'small',
    x: 888,
    y: 1516
  }, {
    type: 'clay',
    size: 'large',
    x: 894,
    y: 1240
  }, {
    type: 'tar',
    x: 1219,
    y: 953,
    size: 'medium'
  }, {
    type: 'tar',
    x: 590,
    y: 1716,
    size: 'small'
  }, {
    type: 'sand',
    x: 975,
    y: 1255,
    size: 'small'
  }, {
    type: 'peat',
    x: 443,
    y: 1438,
    size: 'large'
  }, {
    type: 'clay',
    x: 514,
    y: 2373,
    size: 'large'
  }, {
    type: 'clay',
    x: 3677,
    y: 3691,
    size: 'small'
  }, {
    type: 'clay',
    x: 670,
    y: 2355,
    size: 'large'
  }, {
    type: 'tar',
    x: 903,
    y: 320,
    size: 'small'
  }, {
    type: 'tar',
    x: 710,
    y: 494
  }, {
    type: 'clay',
    x: 1697,
    y: 3772,
    size: 'medium'
  }, {
    type: 'tar',
    x: 2125,
    y: 1019,
    size: 'tar'
  }, {
    type: 'clay',
    x: 400,
    y: 1968,
    size: 'small'
  }, {
    type: 'tar',
    x: 1171,
    y: 3693,
    size: 'large'
  }, {
    type: 'tar',
    x: 500,
    y: 470,
    size: 'large'
  }, {
    type: 'mine',
    x: 966,
    y: 793,
    ores: ['iron', 'copper', 'lead', 'zinc', 'silver', 'gold'],
    features: ['forge', 'large anvil']
  }, {
    type: 'mine',
    x: 765,
    y: 3726,
    ores: ['iron'],
    features: ['forge', 'large anvil']
  }, {
    type: 'mine',
    x: 596,
    y: 1096,
    ores: ['iron', 'silver']
  }, {
    type: 'mine',
    x: 886,
    y: 2196,
    ores: ['iron', 'copper'],
    features: ['forge', 'large anvil']
  }
];
